name: Shortcut Iteration
description: Create an iteration on Shortcut
branding:
  icon: arrow-right-circle
  color: purple
inputs:
  shortcutToken:
    description: Shortcut API auth token
    required: true
  name:
    description: Iteration name
    required: true
  description:
    description: Iteration description
    required: false
  canCreateIfNoNewStories:
    description: Create the iteration even if there aren't any stories to assign to it
    required: false
  completedStateId:
    description: Workflow state id for the completed state
    required: true
  completedAfter:
    description: Datetime when the stories were moved to the completed state
    required: true

outputs:
  iteration-created:
    description: Was the iteration created
  url:
    description: Iteration URL
runs:
  using: "node12"
  main: "index.js"
